spring:
  kafka:
    consumer:
      bootstrap-servers: ny001-b-kafka.webex.com:9092
    producer:
      bootstrap-servers: ny001-b-kafka.webex.com:9092
      batch-size: 30
      buffer-memory: 2097152
      retries: 3
      acks: all
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    ssl:
#      trust-store-password: changeit
#    security:
#      protocol: SASL_SSL
#    jaas:
#      enabled: true
    properties:
      max:
        block:
          ms: 10000
        in:
          flight:
            requests:
              per:
                connection: 1
      request:
        timeout:
          ms: 600000
#      sasl:
#        jaas:
#          config: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;
#        mechanism: OAUTHBEARER
#        login:
#          callback:
#            handler:
#              class: com.cisco.webex.kafka.common.security.Oauth2ClientAuthenticateCallbackHandler


platform:
  kafka:
#    producer:
#      resending:
#        enable: true
#        app-token: APP_AIBRIDGE
#        wns-vip: https://wsq1wns.dmz.webex.com/wbxnotification/retryservice/api/v1/message
    notification:
      enabled: true
      message:
        suite-recording:
          enable: true
          topic: dmz1_suite_recording_webex_notification
          ai-integration-group: ai_integration_group_6
        summary:
          enable: true
          topic: dmz1_suite_recording_webex_notification
          ai-integration-group: ai_integration_group_6
        summary-transcript:
          enable: true
          topic: dmz1_suite_recording_webex_notification
          ai-integration-group: ai_integration_group_6


