spring:
  config:
    import:
      - "classpath:conf/cache.properties"
      - "classpath:conf/kafka.properties"
      - "classpath:conf/redis.properties"
      - "classpath:conf/security.properties"
      - "classpath:conf/thread.properties"