spring:
  config:
    import:
      - "classpath:conf/cache.properties"
      - "classpath:conf/kafka.properties"
      - "classpath:conf/mybatis-plus.properties"
      - "classpath:conf/mysql.properties"
      - "classpath:conf/redis.properties"
      - "classpath:conf/security.properties"
      - "classpath:conf/thread.properties"

#logging:
#  level:
#    org.apache.kafka.clients.consumer: DEBUG
#    org.springframework.kafka.core.KafkaTemplate: DEBUG
#    org.springframework.kafka.listener.KafkaMessageListenerContainer: DEBUG