server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  # consul注册中心地址
  cloud:
    consul:
      host: 192.168.10.100
      port: 8500
      discovery:
        # 对外暴露的consul服务名称
        service-name: ${spring.application.name}