server:
  port: 9527

spring:
  application:
    name: redis_study
  data:
    redis:
      host: 192.168.2.100
      port: 6379
      password: 123456
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
